image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-client-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/${CI_CI_PROJECT_NAME}-client" -f Dockerfile-client .
    - docker push "$CI_REGISTRY_IMAGE/${CI_CI_PROJECT_NAME}-client"
  only:
    - master

build-server-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/${CI_CI_PROJECT_NAME}-server" -f Dockerfile-server .
    - docker push "$CI_REGISTRY_IMAGE/${CI_CI_PROJECT_NAME}-server"
  only:
    - master

build-client:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/${CI_CI_PROJECT_NAME}-client:$CI_COMMIT_REF_SLUG" -f Dockerfile-client .
    - docker push "$CI_REGISTRY_IMAGE/${CI_CI_PROJECT_NAME}-client:$CI_COMMIT_REF_SLUG"
  except:
    - master

build-server:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/${CI_CI_PROJECT_NAME}-server:$CI_COMMIT_REF_SLUG" -f Dockerfile-server .
    - docker push "$CI_REGISTRY_IMAGE/${CI_CI_PROJECT_NAME}-server:$CI_COMMIT_REF_SLUG"
  except:
    - master
